/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState, Suspense } from 'react'
import { useGLTF } from '@react-three/drei'
import { OrbitControls } from "@react-three/drei";
import { Canvas } from "@react-three/fiber";

export default function About({ ...props }) {

  const [active, setActive] = useState(false)


  const group = useRef()
  const { nodes, materials } = useGLTF('/about.gltf')
  return (

  
    <group ref={group} {...props} dispose={null}>
      <mesh 
      onClick={() => setActive(!active)}
      scale={active ? 1.2 : 1} 
      geometry={nodes.Text.geometry} 
      material={materials.Material} 
      position={[-0.07, 2, -1.06]} 
      rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/about.gltf')
