/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { TextureLoader, Vector3 } from 'three'
import Earthday from "./../../../src/earth.jpg"
import { useFrame, useLoader } from '@react-three/fiber'




export default function Earth2({ ...props }) {
  const group = useRef()
  const earthRotation = useRef()
 

  useFrame (() => {
    if (earthRotation.current){
      earthRotation.current?.rotateY(.0007)
    }
  })

  const [colorMap] = useLoader(TextureLoader,[Earthday])
  const { nodes } = useGLTF('/earth2.gltf')
  return (
    <group ref={group} {...props} dispose={null} scale={3}  >
      <group ref={earthRotation} >
      <mesh  geometry={nodes.earth.geometry}   >
      <meshStandardMaterial map={colorMap} />
      </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/earth2.gltf')
