/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { TextureLoader } from 'three'
import Earthday from "./../../../src/earth.jpg"
import { useLoader } from '@react-three/fiber'

export default function Earth2({ ...props }) {
  const group = useRef()
  const [colorMap] = useLoader(TextureLoader,[Earthday])
  const { nodes } = useGLTF('/earth2.gltf')
  return (
    <group ref={group} {...props} dispose={null}  >
      <mesh geometry={nodes.earth.geometry}  rotation={[0, 0, 0]} scale={4} >
      <meshStandardMaterial map={colorMap} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/earth2.gltf')
