/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function   Jet({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/jet.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 5.77, -2.41]}>
        <group position={[0, -0.94, 2.53]} rotation={[Math.PI / 2, 0, 0]} scale={[0.042, .331, 0.042]}>
          <mesh geometry={nodes.Cylinder.geometry} material={materials.uçak} />
          <mesh geometry={nodes.Cylinder_1.geometry} material={materials.cam} />
          <mesh geometry={nodes.Cylinder_2.geometry} material={materials.kantuc} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/jet.gltf')
