/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { Suspense, useRef } from 'react'
import { Canvas } from "@react-three/fiber";
import { OrbitControls } from "@react-three/drei";

import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/shoe.gltf')
  return (
    <div className="Container" style={{ width:"100%", height:"100vh" } }>
    <Canvas camera={{ fov: 70, position: [0,0,10]}}>
    <Suspense fallback={null}>
      <ambientLight intensity={3}/>

      <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.shoe.geometry} material={materials.laces} />
      <mesh geometry={nodes.shoe_1.geometry} material={materials.mesh} />
      <mesh geometry={nodes.shoe_2.geometry} material={materials.caps} />
      <mesh geometry={nodes.shoe_3.geometry} material={materials.inner} />
      <mesh geometry={nodes.shoe_4.geometry} material={materials.sole} />
      <mesh geometry={nodes.shoe_5.geometry} material={materials.stripes} />
      <mesh geometry={nodes.shoe_6.geometry} material={materials.band} />
      <mesh geometry={nodes.shoe_7.geometry} material={materials.patch} />
    </group>
   
     <directionalLight intensity={1} position={[0,0,50]} color="blue" />

      <OrbitControls />
   </Suspense>

    </Canvas>
   </div>

   
  )
}

useGLTF.preload('/shoe.gltf')
