/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/mdvr.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Window4Cube3.geometry} material={materials.Marble} position={[-13.38, 3.8, 3.58]} rotation={[-Math.PI, -0.01, -Math.PI]} scale={[0.1, 1.82, 2.15]} />
      <mesh geometry={nodes.Window4Cube2_collider.geometry} material={nodes.Window4Cube2_collider.material} position={[-16.95, 6.66, 0.3]} rotation={[-Math.PI, -0.01, -Math.PI]} scale={[0.1, 0.62, 3]} />
      <mesh geometry={nodes.Window4Cube2.geometry} material={materials.Darkglass} position={[-16.95, 6.66, 0.3]} rotation={[-Math.PI, -0.01, -Math.PI]} scale={[0.1, 0.62, 3]} />
      <mesh geometry={nodes.Window3Cube1_collider.geometry} material={materials['Glass  Invisible']} position={[-6.15, 15.63, 0.81]} rotation={[0, -1.56, 0]} scale={[0.1, 2.81, 5.17]} />
      <group position={[-6.15, 15.63, 0.81]} rotation={[0, -1.56, 0]} scale={[0.1, 2.81, 5.17]}>
        <mesh geometry={nodes.Cube034.geometry} material={materials['Glass  Invisible']} />
        <mesh geometry={nodes.Cube034_1.geometry} material={materials['Glass  Invisible']} />
      </group>
      <group position={[-8, 3.73, 1.4]} rotation={[-Math.PI, 1.56, -Math.PI]} scale={[0.07, 1.82, 5.4]}>
        <mesh geometry={nodes.Cube043.geometry} material={materials.Marble} />
        <mesh geometry={nodes.Cube043_1.geometry} material={materials.Popart} />
      </group>
      <mesh geometry={nodes.Window2Cube2_collider.geometry} material={nodes.Window2Cube2_collider.material} position={[-8.98, 6.65, 3.14]} rotation={[0, -1.56, 0]} scale={[0.1, 0.62, 8.01]} />
      <mesh geometry={nodes.Window2Cube2.geometry} material={materials.Darkglass} position={[-8.98, 6.65, 3.14]} rotation={[0, -1.56, 0]} scale={[0.1, 0.62, 8.01]} />
      <group position={[-6.03, 17.65, 6.64]} rotation={[0, -1.56, 0]} scale={[0.1, 0.65, 5]}>
        <mesh geometry={nodes.Cube025.geometry} material={materials['Glass  Invisible']} />
        <mesh geometry={nodes.Cube025_1.geometry} material={materials['Glass  Invisible']} />
      </group>
      <mesh geometry={nodes.Window1Cube3.geometry} material={materials.Marble} position={[-2.64, 3.8, 3.52]} rotation={[-Math.PI, -0.01, -Math.PI]} scale={[0.1, 1.82, 2.15]} />
      <mesh geometry={nodes.Window1Cube2_collider.geometry} material={materials['Glass  Invisible']} position={[-0.97, 8.52, 0.16]} rotation={[-Math.PI, -0.01, -Math.PI]} scale={[0.1, 2.52, 3]} />
      <mesh geometry={nodes.Window1Cube2.geometry} material={materials['Glass  Invisible']} position={[-0.97, 8.52, 0.16]} rotation={[-Math.PI, -0.01, -Math.PI]} scale={[0.1, 2.52, 3]} />
      <mesh geometry={nodes.Window1Cube1_collider.geometry} material={materials['Glass  Invisible']} position={[-0.98, 15.53, 3.69]} rotation={[-Math.PI, -0.01, -Math.PI]} scale={[0.1, 2.7, 3]} />
      <mesh geometry={nodes.Window1Cube1.geometry} material={materials['Glass  Invisible']} position={[-0.98, 15.53, 3.69]} rotation={[-Math.PI, -0.01, -Math.PI]} scale={[0.1, 2.7, 3]} />
      <mesh geometry={nodes.WallCube2.geometry} material={materials.Laocoon} position={[-8.92, 8.56, -2.76]} rotation={[-Math.PI, -0.01, -Math.PI]} scale={[7.96, 2.58, 0.1]} />
      <mesh geometry={nodes.Wall7Cube1_collider.geometry} material={materials.Marble} position={[-16.17, 14.26, 2.95]} rotation={[0, 0.01, 0]} scale={[-0.75, 1.21, 0.1]} />
      <mesh geometry={nodes.Wall7Cube1.geometry} material={materials.Marble} position={[-16.17, 14.26, 2.95]} rotation={[0, 0.01, 0]} scale={[-0.75, 1.21, 0.1]} />
      <mesh geometry={nodes.Wall6Cube1_collider.geometry} material={materials.Marble} position={[-13.84, 14.24, 4.76]} rotation={[0, -1.56, 0]} scale={[-1.9, 1.21, 0.1]} />
      <mesh geometry={nodes.Wall6Cube1.geometry} material={materials.Marble} position={[-13.84, 14.24, 4.76]} rotation={[0, -1.56, 0]} scale={[-1.9, 1.21, 0.1]} />
      <mesh geometry={nodes.Wall5Cube1_collider.geometry} material={materials.Marble} position={[-16.81, 14.26, 3.83]} rotation={[0, -1.56, 0]} scale={[2.86, 1.21, 0.1]} />
      <mesh geometry={nodes.Wall5Cube1.geometry} material={materials.Marble} position={[-16.81, 14.26, 3.83]} rotation={[0, -1.56, 0]} scale={[2.86, 1.21, 0.1]} />
      <mesh geometry={nodes.Wall1cube3.geometry} material={materials.Marble} position={[-8.08, 3.77, 5.61]} rotation={[-Math.PI, -0.01, -Math.PI]} scale={[5.35, 1.82, 0.07]} />
      <mesh geometry={nodes.Switch.geometry} material={nodes.Switch.material} position={[-9.45, 7.96, -2.51]} rotation={[-Math.PI, -0.01, -Math.PI]} scale={[0.5, 0.84, 0.2]} />
      <group position={[-4.75, 13.16, 5.55]} rotation={[-Math.PI, -0.01, -Math.PI]} scale={[0.15, 0.11, 1]}>
        <mesh geometry={nodes.Cube058.geometry} material={materials.Marble} />
        <mesh geometry={nodes.Cube058_1.geometry} material={materials.Laocoon} />
      </group>
      <group position={[-4.75, 13.16, 5.55]} rotation={[-Math.PI, -0.01, -Math.PI]} scale={[0.15, 0.11, 1]}>
        <mesh geometry={nodes.Cube015.geometry} material={materials.Marble} />
        <mesh geometry={nodes.Cube015_1.geometry} material={materials.Marble} />
      </group>
      <mesh geometry={nodes.RoofCube3.geometry} material={materials.Marble} position={[-8, 5.55, 3.5]} rotation={[Math.PI, -0.01, Math.PI / 2]} scale={[0.06, 5.35, 2.19]} />
      <mesh geometry={nodes.RoofCube2_collider.geometry} material={materials['Glass  Invisible']} position={[-8.89, 11.01, 0.2]} rotation={[Math.PI, -0.01, Math.PI / 2]} scale={[0.08, 7.95, 2.95]} />
      <mesh geometry={nodes.RoofCube2.geometry} material={materials['Glass  Invisible']} position={[-8.89, 11.01, 0.2]} rotation={[Math.PI, -0.01, Math.PI / 2]} scale={[0.08, 7.95, 2.95]} />
      <mesh geometry={nodes.RoofCube1.geometry} material={materials['Glass  Invisible']} position={[-6.11, 18.33, 3.73]} rotation={[Math.PI, -0.01, Math.PI / 2]} scale={[0.1, 5.18, 3]} />
      <mesh geometry={nodes.popart_collider.geometry} material={materials['Glass  Invisible']} position={[-8.97, 14.95, 6.68]} rotation={[-Math.PI, -0.01, -Math.PI]} scale={[-7.97, 2.13, 0.1]} />
      <mesh geometry={nodes.popart.geometry} material={materials.Darkglass} position={[-8.97, 14.95, 6.68]} rotation={[-Math.PI, -0.01, -Math.PI]} scale={[-7.97, 2.13, 0.1]} />
      <mesh geometry={nodes.Light9c3.geometry} material={materials.glow} position={[-2.63, 3.77, 1.37]} rotation={[Math.PI / 2, 0, 0]} scale={[-0.11, -0.09, -1.86]} />
      <mesh geometry={nodes.Light8c3.geometry} material={materials.glow} position={[-8, 5.53, 1.34]} rotation={[0, Math.PI / 2, 0]} scale={[-0.08, -0.1, 5.41]} />
      <mesh geometry={nodes.Light7c3.geometry} material={materials.glow} position={[-8, 5.53, 5.7]} rotation={[0, Math.PI / 2, 0]} scale={[-0.06, -0.1, 5.41]} />
      <mesh geometry={nodes.Light6c3.geometry} material={materials.glow} position={[-8, 1.98, 5.71]} rotation={[0, Math.PI / 2, 0]} scale={[-0.08, -0.1, 5.41]} />
      <mesh geometry={nodes.Light5c3.geometry} material={materials.glow} position={[-8, 1.98, 1.35]} rotation={[0, Math.PI / 2, 0]} scale={[-0.08, -0.1, 5.41]} />
      <mesh geometry={nodes.Light4c3.geometry} material={materials.glow} position={[-13.45, 1.97, 3.56]} scale={[-0.08, -0.1, -2.14]} />
      <mesh geometry={nodes.Light3c3.geometry} material={materials.glow} position={[-13.43, 5.57, 3.56]} scale={[-0.07, -0.1, -2.14]} />
      <mesh geometry={nodes.Light2c3.geometry} material={materials.glow} position={[-2.6, 5.52, 3.49]} scale={[-0.09, -0.1, -2.14]} />
      <mesh geometry={nodes.Light1c3.geometry} material={materials.glow} position={[-2.6, 1.98, 3.52]} scale={[-0.08, -0.1, -2.14]} />
      <mesh geometry={nodes.Light11c3001.geometry} material={materials.glow} position={[-13.4, 3.8, 1.32]} rotation={[Math.PI / 2, 0, 0]} scale={[-0.11, -0.09, -1.89]} />
      <mesh geometry={nodes.Light11c3.geometry} material={materials.glow} position={[-13.41, 3.8, 5.7]} rotation={[Math.PI / 2, 0, 0]} scale={[-0.11, -0.09, -1.89]} />
      <mesh geometry={nodes.Light10c3.geometry} material={materials.glow} position={[-2.63, 3.77, 5.7]} rotation={[Math.PI / 2, 0, 0]} scale={[-0.11, -0.09, -1.85]} />
      <mesh geometry={nodes.FloorCube1_collider.geometry} material={materials['Glass  Invisible']} position={[-8.92, 12.94, 3.77]} rotation={[-Math.PI, -0.01, -Math.PI]} scale={[8, 0.1, 3]} />
      <mesh geometry={nodes.FloorCube1.geometry} material={materials.wood} position={[-8.92, 12.94, 3.77]} rotation={[-Math.PI, -0.01, -Math.PI]} scale={[8, 0.1, 3]} />
      <mesh geometry={nodes.Floor1Cube3_collider.geometry} material={materials.wood} position={[-8.08, 1.98, 3.51]} rotation={[-Math.PI, -0.01, -Math.PI]} scale={[5.43, 0.06, 2.18]} />
      <mesh geometry={nodes.Floor1Cube3.geometry} material={materials.Marble} position={[-8.08, 1.98, 3.51]} rotation={[-Math.PI, -0.01, -Math.PI]} scale={[5.43, 0.06, 2.14]} />
      <mesh geometry={nodes.Floor1Cube2_collider.geometry} material={materials['Glass  Invisible']} position={[-8.98, 6.06, 0.28]} rotation={[-Math.PI, -0.01, -Math.PI]} scale={[8.06, 0.08, 2.95]} />
      <mesh geometry={nodes.Floor1Cube2.geometry} material={materials.wood} position={[-8.98, 6.06, 0.28]} rotation={[-Math.PI, -0.01, -Math.PI]} scale={[8.06, 0.08, 2.95]} />
      <mesh geometry={nodes.Deck_collider.geometry} material={materials.wood} position={[-12.43, 15.53, 3.77]} rotation={[Math.PI, -0.01, Math.PI / 2]} scale={[0.1, 4.46, 2.82]} />
      <mesh geometry={nodes.Deck.geometry} material={materials.wood} position={[-12.43, 15.53, 3.77]} rotation={[Math.PI, -0.01, Math.PI / 2]} scale={[0.1, 4.46, 2.82]} />
      <mesh geometry={nodes.Ground.geometry} material={materials.Material} position={[-9.17, 0.04, -2.72]} scale={[10, 0.05, 6.49]} />
      <mesh geometry={nodes.Rails1.geometry} material={materials.Darkglass} position={[-14.05, 16.27, 0.84]} scale={[2.9, 0.69, 0.05]} />
      <mesh geometry={nodes.Rails2.geometry} material={materials.Darkglass} position={[-16.89, 16.27, 3.75]} rotation={[0, Math.PI / 2, 0]} scale={[2.9, 0.69, 0.05]} />
      <mesh geometry={nodes.Cube004.geometry} material={nodes.Cube004.material} position={[-13.9, 6.63, -0.24]} rotation={[-Math.PI, -0.01, -Math.PI]} scale={[2.05, 0.42, 0.6]} />
      <mesh geometry={nodes.btndec001.geometry} material={nodes.btndec001.material} position={[-16.72, 14.33, 5.94]} rotation={[0, -1.56, 0]} scale={[0.5, 0.55, 0.15]} />
      <mesh geometry={nodes.Rails1_collider.geometry} material={materials['Darkglass.001']} position={[-14.05, 16.27, 0.84]} scale={[2.9, 0.69, 0.05]} />
      <mesh geometry={nodes.Rails2_collider.geometry} material={materials['Darkglass.002']} position={[-16.89, 16.27, 3.75]} rotation={[0, Math.PI / 2, 0]} scale={[2.9, 0.69, 0.05]} />
      <mesh geometry={nodes.Ground_collider.geometry} material={materials['Material.001']} position={[-9.17, 0.04, -2.72]} scale={[10, 0.05, 6.49]} />
      <mesh geometry={nodes.RoofCube1_collider.geometry} material={materials['Glass  Invisible.001']} position={[-6.11, 18.33, 3.73]} rotation={[Math.PI, -0.01, Math.PI / 2]} scale={[0.1, 5.18, 3]} />
      <mesh geometry={nodes.WallCube2_collider.geometry} material={materials['Laocoon.001']} position={[-8.92, 8.56, -2.76]} rotation={[-Math.PI, -0.01, -Math.PI]} scale={[7.96, 2.58, 0.1]} />
    </group>
  )
}

useGLTF.preload('/mdvr.gltf')
