/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/mvdrNC.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Window9Cube2.geometry} material={materials.Marble} position={[-16.87, 8.36, -0.47]} scale={[0.1, 2.34, 2.18]} />
      <mesh geometry={nodes.Window5Cube3.geometry} material={materials.Darkglass} position={[-13.41, 2.71, 3.49]} scale={[0.1, 0.66, 2.11]} />
      <group position={[-0.96, 6.65, 2.52]} rotation={[Math.PI, -0.01, 0]} scale={[-0.1, -0.62, -0.85]}>
        <mesh geometry={nodes.Cube057.geometry} material={materials['Glass  Invisible']} />
        <mesh geometry={nodes.Cube057_1.geometry} material={materials.glow} />
      </group>
      <group position={[-8.03, 3.82, 5.63]} rotation={[0, Math.PI / 2, 0]} scale={[0.07, 1.82, 5.5]}>
        <mesh geometry={nodes.Cube043.geometry} material={materials.Marble} />
        <mesh geometry={nodes.Cube043_1.geometry} material={materials.Popart} />
      </group>
      <group position={[-7.19, 6.65, 3.27]} rotation={[0, -Math.PI / 2, 0]} scale={[0.1, 0.62, 6.25]}>
        <mesh geometry={nodes.Cube030.geometry} material={materials['Glass  Invisible']} />
        <mesh geometry={nodes.Cube030_1.geometry} material={materials.glow} />
      </group>
      <mesh geometry={nodes.Window1Cube3.geometry} material={materials['Glass  Invisible']} position={[-2.64, 3.8, 3.52]} rotation={[Math.PI, 0, Math.PI]} scale={[0.1, 1.82, 2.15]} />
      <mesh geometry={nodes.window1Cube2.geometry} material={materials.Darkglass} position={[-0.84, 8.3, -0.46]} scale={[0.15, 2.32, 2.18]} />
      <mesh geometry={nodes.Window1Cube1.geometry} material={materials['Glass  Invisible']} position={[-1.52, 15.35, 4.36]} rotation={[Math.PI, -0.01, Math.PI]} scale={[0.09, 2.54, 2.14]} />
      <group position={[-7.9, 8.07, -0.78]} rotation={[Math.PI, 0, Math.PI]} scale={[5.6, 2, 0.15]}>
        <mesh geometry={nodes.Cube014.geometry} material={materials.Laocoon} />
        <mesh geometry={nodes.Cube014_1.geometry} material={materials.Lacoon2} />
      </group>
      <mesh geometry={nodes.WallBanksy.geometry} material={materials.Banksy} position={[-4.76, 15.38, 2.26]} scale={[3.25, 2.5, 0.1]} />
      <mesh geometry={nodes.Wall9CUbe2.geometry} material={materials.Marble} position={[-15.09, 8.31, 3.29]} scale={[1.75, 2.29, 0.1]} />
      <mesh geometry={nodes.Wall9cube1.geometry} material={materials['Glass  Invisible']} position={[-12.45, 14.13, 0.69]} scale={[4.49, 1.33, 0.1]} />
      <mesh geometry={nodes.Wall8Cube1.geometry} material={materials['Glass  Invisible']} position={[-8.06, 14.19, 1.39]} scale={[0.1, 1.38, 0.8]} />
      <group position={[-13.4, 14.13, 6.59]} scale={[3.49, 1.33, 0.1]}>
        <mesh geometry={nodes.Cube020.geometry} material={materials.Marble} />
        <mesh geometry={nodes.Cube020_1.geometry} material={materials['Glass  Invisible']} />
      </group>
      <mesh geometry={nodes.Wall6LC.geometry} material={materials.Marble} position={[-13.31, 6.68, 4.57]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.1, -0.59, -1.16]} />
      <mesh geometry={nodes.Wall6Cube2.geometry} material={materials.Marble} position={[-13.33, 8.29, 1.29]} scale={[0.1, 2.22, 2.09]} />
      <mesh geometry={nodes.Wall6Cube1.geometry} material={materials.Marble} position={[-13.84, 14.24, 4.76]} rotation={[-Math.PI, 1.56, 0]} scale={[-1.9, -1.21, -0.1]} />
      <mesh geometry={nodes.Wall5Cube1.geometry} material={materials.Marble} position={[-16.88, 14.11, 3.68]} rotation={[0, -Math.PI / 2, 0]} scale={[-3.02, -1.37, -0.1]} />
      <mesh geometry={nodes.Wall4LC.geometry} material={materials.Marble} position={[-15.04, 5.26, 5.63]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-1.72, -2.01, -0.1]} />
      <mesh geometry={nodes.Wall3LC.geometry} material={materials.Marble} position={[-13.39, 4.68, 2.7]} scale={[0.09, 1.42, 1.4]} />
      <group position={[-15.04, 4.2, 1.38]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-1.71, -1.02, -0.1]}>
        <mesh geometry={nodes.Cube082.geometry} material={materials.Darkglass} />
        <mesh geometry={nodes.Cube082_1.geometry} material={materials.Marble} />
      </group>
      <group position={[-5.48, 14.89, 6.56]} scale={[4.5, 2.1, 0.1]}>
        <mesh geometry={nodes.Cube001.geometry} material={materials.Marble} />
        <mesh geometry={nodes.Cube001_1.geometry} material={materials.Marble} />
      </group>
      <mesh geometry={nodes.Switch001.geometry} material={materials.Darkglass} position={[-13.56, 4.7, 3.28]} rotation={[0, Math.PI / 2, 0]} scale={[0.5, 0.84, 0.2]} />
      <mesh geometry={nodes.Switch.geometry} material={materials.Marble} position={[-3.48, 7.4, -0.59]} rotation={[Math.PI, -0.01, Math.PI]} scale={[0.5, 0.84, 0.11]} />
      <group position={[-4.75, 13.13, 5.54]} rotation={[Math.PI, -0.01, Math.PI]} scale={[0.15, 0.11, 0.89]}>
        <mesh geometry={nodes.Cube015.geometry} material={materials.Marble} />
        <mesh geometry={nodes.Cube015_1.geometry} material={materials.Darkglass} />
        <mesh geometry={nodes.Cube015_2.geometry} material={materials.glow} />
      </group>
      <mesh geometry={nodes.s002.geometry} material={materials.Marble} position={[-11.72, 7.25, 1.08]} rotation={[0, -0.56, 0.07]} scale={[0.11, 0.06, 0.06]} />
      <mesh geometry={nodes.s001.geometry} material={materials.Marble} position={[-9.33, 7.25, 1.08]} rotation={[0, -0.56, 0.07]} scale={[0.11, 0.06, 0.06]} />
      <mesh geometry={nodes.S.geometry} material={nodes.S.material} position={[-9.33, 7.25, 1.08]} rotation={[0, -0.56, 0.07]} scale={[0.11, 0.06, 0.06]} />
      <mesh geometry={nodes.s.geometry} material={nodes.s.material} position={[-11.72, 7.25, 1.08]} rotation={[0, -0.56, 0.07]} scale={[0.11, 0.06, 0.06]} />
      <mesh geometry={nodes.RoofLC.geometry} material={materials.Marble} position={[-15.06, 7.17, 4.52]} scale={[1.74, 0.1, 1.21]} />
      <mesh geometry={nodes.RoofCube3.geometry} material={materials.Marble} position={[-7.91, 5.61, 3.51]} rotation={[Math.PI, 0, Math.PI]} scale={[5.36, 0.06, 2.14]} />
      <mesh geometry={nodes.RoofCube2.geometry} material={materials.Marble} position={[-8.99, 10.53, 0.37]} rotation={[0, 0, -Math.PI / 2]} scale={[0.1, 7.95, 2.35]} />
      <group position={[-5.49, 17.87, 3.05]} scale={[4.5, 0.1, 2.5]}>
        <mesh geometry={nodes.Cube066.geometry} material={materials.Darkglass} />
        <mesh geometry={nodes.Cube066_1.geometry} material={materials.glow} />
      </group>
      <group position={[-13.45, 16.22, 6.55]} scale={[3.47, 0.77, 0.1]}>
        <mesh geometry={nodes.Cube011.geometry} material={materials.Darkglass} />
        <mesh geometry={nodes.Cube011_1.geometry} material={materials.glow} />
      </group>
      <group position={[-8.06, 16.23, 2.54]} rotation={[0, Math.PI / 2, 0]} scale={[1.93, 0.77, 0.05]}>
        <mesh geometry={nodes.Cube012.geometry} material={materials.Darkglass} />
        <mesh geometry={nodes.Cube012_1.geometry} material={materials.glow} />
      </group>
      <group position={[-16.94, 16.23, 3.63]} rotation={[0, Math.PI / 2, 0]} scale={[3.03, 0.77, 0.05]}>
        <mesh geometry={nodes.Cube026.geometry} material={materials.Darkglass} />
        <mesh geometry={nodes.Cube026_1.geometry} material={materials.glow} />
      </group>
      <group position={[-8, 2.62, 1.34]} scale={[5.35, 0.75, 0.05]}>
        <mesh geometry={nodes.Cube031.geometry} material={materials['Glass  Invisible']} />
        <mesh geometry={nodes.Cube031_1.geometry} material={materials['Glass  Invisible']} />
      </group>
      <group position={[-12.47, 16.22, 0.65]} scale={[4.47, 0.77, 0.05]}>
        <mesh geometry={nodes.Cube055.geometry} material={materials.Darkglass} />
        <mesh geometry={nodes.Cube055_1.geometry} material={materials.glow} />
      </group>
      <mesh geometry={nodes.MAinwindowCube2.geometry} material={materials['Glass  Invisible']} position={[-8.94, 8.32, -2.54]} scale={[7.97, 1.61, 0.1]} />
      <mesh geometry={nodes.Light6c3.geometry} material={materials.glow} position={[-8.03, 1.98, 5.71]} rotation={[Math.PI, Math.PI / 2, 0]} scale={[0.08, 0.15, 5.51]} />
      <mesh geometry={nodes.Light5c3.geometry} material={materials.glow} position={[-8, 1.98, 1.35]} rotation={[Math.PI, Math.PI / 2, 0]} scale={[0.08, 0.15, 5.49]} />
      <mesh geometry={nodes.Light4c3.geometry} material={materials.glow} position={[-13.45, 1.97, 3.5]} scale={[-0.08, -0.15, -2.24]} />
      <mesh geometry={nodes.Light1c3.geometry} material={materials.glow} position={[-2.6, 1.98, 3.52]} scale={[-0.09, -0.15, -2.26]} />
      <mesh geometry={nodes.Ground.geometry} material={materials.Bake} position={[-9.17, 0.04, -7.96]} scale={[18.28, 0.09, 10.05]} />
      <mesh geometry={nodes.FloorCube1.geometry} material={materials.Bake} position={[-8.98, 12.79, 3.66]} scale={[8, 0.1, 3]} />
      <mesh geometry={nodes.FloorCL.geometry} material={materials.glow} position={[-15.1, 3.28, 3.53]} scale={[1.7, 0.1, 2.16]} />
      <mesh geometry={nodes.Floor2Cube2.geometry} material={materials.wood} position={[-15.04, 6.12, -0.66]} rotation={[0, 0, -Math.PI]} scale={[-1.76, -0.1, -1.1]} />
      <mesh geometry={nodes.Floor1Cube3.geometry} material={materials.wood} position={[-8.08, 1.96, 3.51]} rotation={[Math.PI, 0, Math.PI]} scale={[5.43, 0.06, 2.14]} />
      <mesh geometry={nodes.Floor1Cube2.geometry} material={materials.wood} position={[-7.17, 6.14, 0.82]} scale={[6.13, 0.1, 2.51]} />
      <mesh geometry={nodes.DetailLC.geometry} material={materials.Marble} position={[-16.86, 5.03, -0.07]} scale={[0.1, 1, 1.38]} />
      <mesh geometry={nodes.Detailcube2.geometry} material={materials.Marble} position={[-15.09, 10.52, 3.03]} scale={[1.85, 0.1, 0.35]} />
      <mesh geometry={nodes.Detail2LC.geometry} material={materials.Marble} position={[-13.4, 4.64, -0.66]} scale={[0.1, 1.45, 1.98]} />
      <mesh geometry={nodes.Deck.geometry} material={materials.wood} position={[-12.48, 15.55, 3.61]} scale={[4.5, 0.1, 3]} />
      <group position={[-8.9, 6.75, -1.82]} rotation={[-Math.PI, 0, -Math.PI / 2]} scale={[0.75, 7.91, 0.79]}>
        <mesh geometry={nodes.Cylinder005_1.geometry} material={materials.Darkglass} />
        <mesh geometry={nodes.Cylinder005_2.geometry} material={materials.wood} />
        <mesh geometry={nodes.Cylinder005_3.geometry} material={materials.glow} />
      </group>
      <mesh geometry={nodes.Cylinder016.geometry} material={materials.Marble} position={[-9.33, 7.14, 1.08]} scale={[0.04, 0.13, 0.04]} />
      <mesh geometry={nodes.Cylinder015.geometry} material={materials.Marble} position={[-9.52, 7.23, 0.97]} rotation={[0.05, -0.54, 1.67]} scale={[0.02, 0.23, 0.02]} />
      <mesh geometry={nodes.Cylinder014.geometry} material={materials.Darkglass} position={[-9.69, 7.19, 0.86]} scale={[0, 0.03, 0]} />
      <mesh geometry={nodes.Cylinder013.geometry} material={materials.Marble} position={[-11.72, 7.14, 1.08]} scale={[0.04, 0.13, 0.04]} />
      <mesh geometry={nodes.Cylinder012.geometry} material={nodes.Cylinder012.material} position={[-11.72, 7.14, 1.08]} scale={[0.04, 0.13, 0.04]} />
      <mesh geometry={nodes.Cylinder011.geometry} material={materials.Marble} position={[-11.91, 7.23, 0.97]} rotation={[0.05, -0.54, 1.67]} scale={[0.02, 0.23, 0.02]} />
      <mesh geometry={nodes.Cylinder010.geometry} material={nodes.Cylinder010.material} position={[-12.08, 7.19, 0.86]} scale={[0, 0.03, 0]} />
      <mesh geometry={nodes.Cylinder009.geometry} material={nodes.Cylinder009.material} position={[-9.33, 7.14, 1.08]} scale={[0.04, 0.13, 0.04]} />
      <mesh geometry={nodes.Cylinder008.geometry} material={nodes.Cylinder008.material} position={[-9.52, 7.23, 0.97]} rotation={[0.05, -0.54, 1.67]} scale={[0.02, 0.23, 0.02]} />
      <mesh geometry={nodes.Cylinder007.geometry} material={materials.Darkglass} position={[-9.69, 7.19, 0.86]} scale={[0, 0.03, 0]} />
      <mesh geometry={nodes.Cylinder006.geometry} material={materials.Marble} position={[-12.08, 7.19, 0.86]} scale={[0, 0.03, 0]} />
      <mesh geometry={nodes.Cylinder005.geometry} material={nodes.Cylinder005.material} position={[-11.91, 7.23, 0.97]} rotation={[0.05, -0.54, 1.67]} scale={[0.02, 0.23, 0.02]} />
      <group position={[-8.9, 9.92, -1.83]} rotation={[-Math.PI, 0, Math.PI / 2]} scale={[0.75, 7.91, 0.79]}>
        <mesh geometry={nodes.Cylinder004_1.geometry} material={materials.Darkglass} />
        <mesh geometry={nodes.Cylinder004_2.geometry} material={materials.glow} />
      </group>
      <mesh geometry={nodes.Cylinder003.geometry} material={materials.Darkglass} position={[-9.88, 7.13, 0.84]} scale={[0.4, 0.03, 0.4]} />
      <mesh geometry={nodes.Cylinder002.geometry} material={materials.Popart} position={[-9.88, 7.02, 0.84]} scale={[0.5, 0.1, 0.5]} />
      <mesh geometry={nodes.Cylinder001.geometry} material={materials.Darkglass} position={[-12.25, 7.13, 0.84]} scale={[0.4, 0.03, 0.4]} />
      <mesh geometry={nodes.Cylinder.geometry} material={materials.Popart} position={[-12.25, 7.02, 0.84]} scale={[0.5, 0.1, 0.5]} />
      <mesh geometry={nodes.CurveCube2.geometry} material={materials.Marble} position={[-15.13, 5.23, 0.48]} rotation={[0, 0, -Math.PI / 2]} scale={[1.02, 1.83, 1]} />
      <group position={[-5.49, 16.98, 5.66]} rotation={[0, 0, -Math.PI / 2]} scale={[1, 4.5, 1]}>
        <mesh geometry={nodes.Cylinder006_1.geometry} material={materials.Darkglass} />
        <mesh geometry={nodes.Cylinder006_2.geometry} material={materials.glow} />
      </group>
      <mesh geometry={nodes.Console.geometry} material={materials.Marble} position={[-11.05, 6.63, 0.8]} rotation={[Math.PI, -0.01, Math.PI]} scale={[2.05, 0.42, 0.6]} />
      <mesh geometry={nodes.btndec001.geometry} material={materials.Popart} position={[-15.4, 14.33, 6.46]} scale={[0.5, 0.55, 0.15]} />
    </group>
  )
}

useGLTF.preload('/mvdrNC.glb')
