/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: ar-watches (https://sketchfab.com/ar-watches)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/tag-heuer-monaco-x-gulf-watch-31ba7140fb3146b2af3cbdc13022421c
title: Tag Heuer Monaco X GULF Watch
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Watch({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/watch-v1.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Object005_glass_0.geometry} material={materials.glass} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Object006_watch_0.geometry} material={materials.watch} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/watch-v1.glb')
